# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-Scalar-MarginOfError
version:      0.03
version_from: lib/Tie/Scalar/MarginOfError.pm
installdirs:  site
requires:
    Test::More:                    0.47
    Tie::Scalar:                   1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
